# Generated by Django 5.2.5 on 2025-09-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailservices", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("can_view_all_recipients", "Может просматривать всех получателей")
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
